# Importando as bibliotecas

In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np
from collections import Counter
import os
import sys
sys.path.insert(0, os.path.abspath('../Util'))
from dados import ProcessarDados

In [2]:
# Dataset

In [3]:
procData = ProcessarDados("../dataset/norm_bin_10_FEATURES_M17_CM6b_TH199.csv")

In [4]:
# Funções

In [5]:
# funcção que treina e testa o modelo armazenando as métricas
# retorna um dicionário cotendo os valores das métricas de cada rodada
def treinamento_teste(epocas = 10, k_folds = 5, exibir_matriz_confusao=False, exibir_metricas=False):
    
    #array para armazenar as das métricas de cada rodada
    resultados_accuracy = []
    resultados_precision = []
    resultados_recall = []
    resultados_f1 = []
    resultados_parametros = []
    
    #dicionário das métricas
    resultados_gerais = {}

    for i in range(epocas):
        # divisão os dados 
        X_train, X_test, y_train, y_test = procData.holdout(0.2)
        #print(Counter(y_test))

        # realizando o grid search para encontrar a melhor K-Vizinhos, 
        # considerando a acurácia (taxa de acerto)
        # aqui o método GridSearchCV é configurado para subdividir os dados de treino em k_folds
        clf = KNeighborsClassifier()
        grid_knn = GridSearchCV(clf, param_grid, cv=k_folds, scoring='accuracy', verbose=0, n_jobs=-1)
        grid_knn.fit(X_train, y_train)
        
        # Treinando do modelo com os melhores parametros encontrados
        grid_knn.best_params_
        Kvizinhos_best = int(grid_knn.best_params_['n_neighbors']) 
        distancia_best = grid_knn.best_estimator_.weights
        KNN = KNeighborsClassifier(n_neighbors=Kvizinhos_best, weights=distancia_best, metric='minkowski', p = 2)
        KNN.fit(X_train, y_train)

        #testando o modelo
        y_pred = KNN.predict(X_test)
        if exibir_matriz_confusao:
            print(confusion_matrix(y_test, y_pred))

        # calculado as metricas
        accuracy = metrics.accuracy_score(y_test, y_pred)
        precision = metrics.precision_score(y_test, y_pred)
        recall = metrics.recall_score(y_test, y_pred)
        f1_score = 2 * (precision * recall) / (precision + recall)

        # armazenando as métricas
        resultados_accuracy.append(accuracy)
        resultados_precision.append(precision)
        resultados_recall.append(recall)
        resultados_f1.append(f1_score)

        best_parametros = "K-Vizinhos(n_neighbors): "+ str(Kvizinhos_best)+ " | Distância(weights): "+distancia_best;
        resultados_parametros.append(best_parametros)


        if exibir_metricas:
            print("Rodada: #",i)
            print(best_parametros)
            print("Accuracy:",accuracy)
            print("Precision:",precision)
            print("Recall:",recall)
            print("F1-Score:",f1_score)
            print("\n")

            
    resultados_gerais['accuracy'] = resultados_accuracy
    resultados_gerais['precision'] = resultados_precision
    resultados_gerais['recall'] = resultados_recall
    resultados_gerais['f1'] = resultados_f1
    
    return resultados_gerais

In [6]:
def tabelaMetricas(nome_modelo, dict_metricas, rodadas=False, salvarResultados=True):
    print ("============================================== "+nome_modelo+" =================================================")
    print ("=================================== TABELA DE MÉTRICAS DO MODELO ===================================")
    
    if(rodadas==False):
        print ("\t Accuracy \t|\t Precision \t|\t Recall \t|\t F1-Score")
        print ("      %.2f +- %.2f" % (np.mean(dict_metricas['accuracy'], axis=0), np.std(dict_metricas['accuracy'], axis=0)),end='       ')
        print ("      %.2f +- %.2f" % (np.mean(dict_metricas['precision'], axis=0), np.std(dict_metricas['precision'], axis=0)),end='    ')
        print ("      %.2f +- %.2f" % (np.mean(dict_metricas['recall'], axis=0), np.std(dict_metricas['recall'], axis=0)),end='       ')
        print ("      %.2f +- %.2f" % (np.mean(dict_metricas['f1'], axis=0), np.std(dict_metricas['f1'], axis=0)))
        print ("====================================================================================================")
        
    if(salvarResultados):
        # save to npy file
        np.save('../resultados/resultados_'+nome_modelo+'.npy', dict_metricas)

# Definindo os parâmetros

In [7]:
#K-Vizinhos
c_range = np.arange(1,25)
#'uniforme': Todos os pontos em cada vizinho têm o mesmo peso.
#'distância': Inverso de sua distância, os vizinhos mais próximos de um ponto de consulta terão uma influência maior do que os vizinhos mais distantes.
distancia = ['uniform', 'distance'] 
param_grid = {'n_neighbors': c_range, 'weights':distancia}
epocas = 50
k_folds = 5
exibir_matriz_confusao = True
exibir_metricas = True

# Treinando e obtendo as métricas do modelo

In [8]:
# treinando o modelo
dict_metricas = treinamento_teste(epocas, k_folds, exibir_matriz_confusao, exibir_metricas)
tabelaMetricas('KNN',dict_metricas)

[[24  1]
 [ 3 92]]
Rodada: # 0
K-Vizinhos(n_neighbors): 10 | Distância(weights): distance
Accuracy: 0.9666666666666667
Precision: 0.989247311827957
Recall: 0.968421052631579
F1-Score: 0.9787234042553192


[[20  7]
 [ 7 86]]
Rodada: # 1
K-Vizinhos(n_neighbors): 6 | Distância(weights): distance
Accuracy: 0.8833333333333333
Precision: 0.9247311827956989
Recall: 0.9247311827956989
F1-Score: 0.9247311827956989


[[25  9]
 [ 0 86]]
Rodada: # 2
K-Vizinhos(n_neighbors): 5 | Distância(weights): distance
Accuracy: 0.925
Precision: 0.9052631578947369
Recall: 1.0
F1-Score: 0.9502762430939227


[[23  5]
 [ 1 91]]
Rodada: # 3
K-Vizinhos(n_neighbors): 12 | Distância(weights): distance
Accuracy: 0.95
Precision: 0.9479166666666666
Recall: 0.9891304347826086
F1-Score: 0.9680851063829786


[[19 11]
 [ 2 88]]
Rodada: # 4
K-Vizinhos(n_neighbors): 11 | Distância(weights): distance
Accuracy: 0.8916666666666667
Precision: 0.8888888888888888
Recall: 0.9777777777777777
F1-Score: 0.931216931216931


[[24 11]
 [ 

[[22  9]
 [ 2 87]]
Rodada: # 42
K-Vizinhos(n_neighbors): 13 | Distância(weights): distance
Accuracy: 0.9083333333333333
Precision: 0.90625
Recall: 0.9775280898876404
F1-Score: 0.9405405405405405


[[18  5]
 [ 5 92]]
Rodada: # 43
K-Vizinhos(n_neighbors): 4 | Distância(weights): distance
Accuracy: 0.9166666666666666
Precision: 0.9484536082474226
Recall: 0.9484536082474226
F1-Score: 0.9484536082474226


[[22  8]
 [ 5 85]]
Rodada: # 44
K-Vizinhos(n_neighbors): 4 | Distância(weights): distance
Accuracy: 0.8916666666666667
Precision: 0.9139784946236559
Recall: 0.9444444444444444
F1-Score: 0.9289617486338798


[[22  6]
 [ 3 89]]
Rodada: # 45
K-Vizinhos(n_neighbors): 5 | Distância(weights): distance
Accuracy: 0.925
Precision: 0.9368421052631579
Recall: 0.967391304347826
F1-Score: 0.9518716577540107


[[29  4]
 [ 6 81]]
Rodada: # 46
K-Vizinhos(n_neighbors): 5 | Distância(weights): distance
Accuracy: 0.9166666666666666
Precision: 0.9529411764705882
Recall: 0.9310344827586207
F1-Score: 0.94186046